# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy to Github Pages

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  next_build_and_export:
    name: "Build website"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run export
        env:
          NODE_ENV: production

      - name: Upload exported website
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: out

  # Only run the steps below if it's the main branch
  deployment:
    name: "Deploy to GitHub Pages"
    if: github.ref == 'refs/heads/main'
    needs: next_build_and_export
    runs-on: ubuntu-latest
    steps:
      - name: Download exported website
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./out

      - name: Create CNAME file with the content www.magdadot.com
        run: echo "www.magdadot.com" > "./out/CNAME"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
